### ISSUE TITLE
Proposal: UpdateNodeTypeParser

### ISSUE THREAD

**Issue by littleGnAl** [AgoraIO-Extensions/terra#1]
The `UpdateNodeTypeParser` does the following things:
- Change the return type of the functions
- Change the parameters' type of the functions

Configuration like below:
```yaml
UpdateNodeTypeParser:
  methods: # The key maybe call `functions`?
    - name: agora::rtc::IRtcEngine::joinChannel
      return_type: # The `return_type`'s keys match the `SimpleType` objects' keys
        name: void
        source: void
        kind: value_t
        is_const: true
        is_builtin_type: true

       parameters:
         - name: channelId
           type: # The `type`'s keys match the `SimpleType` objects' keys
             name: int
             source: int
             kind: value_t
             is_const: true
             is_builtin_type: true
```

Maybe feature in the future
- Change the name of the parameters

```yaml
UpdateNodeTypeParser:
  methods: # The key maybe call `functions`?
    - name: agora::rtc::IRtcEngine::joinChannel
      parameters:
         - name: channelId
           rename: intChannelId
```
